# Generated by Django 4.2.7 on 2024-11-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0003_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=10)),
                ('exercises', models.IntegerField()),
                ('image', models.ImageField(upload_to='workouts/')),
                ('description', models.TextField()),
            ],
        ),
    ]
